### ISSUE TITLE
Crashed after snap a picture and open new window.

### ISSUE THREAD

**Issue by bduyng** [brownemint/Ti-Android-CameraView#10]
Hi @brownemint:
As the title said, I got crashed after the photo is taken and I open a new window (show page). I am using Titanium SDK 5.0.2.GA and pw.custom.androidcamera 0.6.3. Here is my code and crash message:
```
[ERROR] TiApplication: (main) [4616796,4616796] Sending event: exception on thread: main msg:java.lang.RuntimeException: Camera is being used after Camera.release() was called; Titanium 5.0.2,2015/09/30 12:07,92c2265
[ERROR] TiApplication: java.lang.RuntimeException: Camera is being used after Camera.release() was called
[ERROR] TiApplication: 	at android.hardware.Camera.startPreview(Native Method)
[ERROR] TiApplication: 	at pw.custom.androidcamera.CameraViewProxy$2$1.run(CameraViewProxy.java:391)
[ERROR] TiApplication: 	at android.os.Handler.handleCallback(Handler.java:739)
[ERROR] TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] TiApplication: 	at android.os.Looper.loop(Looper.java:135)
[ERROR] TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5292)
[ERROR] TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

```js
cameraView.addEventListener('picture_taken', function(e){
            console.log(e.path);
            Alloy.createController('show', {
                image : e.path
            }).getView().open();
        });
```

Thanks

**Comment by brownemint** [comment]
Thanks for the pull request!
